extend type Mutation {
  """
  ✨ Insert a single `Client` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  client_insert(
    """
    Data object to insert into the table.
    """
    data: Client_Data!
  ): Client_KeyOutput! @fdc_generated(from: "Client", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ExternalJob` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  externalJob_insert(
    """
    Data object to insert into the table.
    """
    data: ExternalJob_Data!
  ): ExternalJob_KeyOutput! @fdc_generated(from: "ExternalJob", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Mechanic` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  mechanic_insert(
    """
    Data object to insert into the table.
    """
    data: Mechanic_Data!
  ): Mechanic_KeyOutput! @fdc_generated(from: "Mechanic", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `OrderPart` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  orderPart_insert(
    """
    Data object to insert into the table.
    """
    data: OrderPart_Data!
  ): OrderPart_KeyOutput! @fdc_generated(from: "OrderPart", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `OrderService` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  orderService_insert(
    """
    Data object to insert into the table.
    """
    data: OrderService_Data!
  ): OrderService_KeyOutput! @fdc_generated(from: "OrderService", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Part` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  part_insert(
    """
    Data object to insert into the table.
    """
    data: Part_Data!
  ): Part_KeyOutput! @fdc_generated(from: "Part", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ServiceCategory` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  serviceCategory_insert(
    """
    Data object to insert into the table.
    """
    data: ServiceCategory_Data!
  ): ServiceCategory_KeyOutput! @fdc_generated(from: "ServiceCategory", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StockMovement` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  stockMovement_insert(
    """
    Data object to insert into the table.
    """
    data: StockMovement_Data!
  ): StockMovement_KeyOutput! @fdc_generated(from: "StockMovement", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserProfile` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userProfile_insert(
    """
    Data object to insert into the table.
    """
    data: UserProfile_Data!
  ): UserProfile_KeyOutput! @fdc_generated(from: "UserProfile", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Vehicle` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vehicle_insert(
    """
    Data object to insert into the table.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput! @fdc_generated(from: "Vehicle", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorkOrder` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workOrder_insert(
    """
    Data object to insert into the table.
    """
    data: WorkOrder_Data!
  ): WorkOrder_KeyOutput! @fdc_generated(from: "WorkOrder", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorkshopService` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workshopService_insert(
    """
    Data object to insert into the table.
    """
    data: WorkshopService_Data!
  ): WorkshopService_KeyOutput! @fdc_generated(from: "WorkshopService", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Client` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  client_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Client_Data!]!
  ): [Client_KeyOutput!]! @fdc_generated(from: "Client", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ExternalJob` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  externalJob_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ExternalJob_Data!]!
  ): [ExternalJob_KeyOutput!]! @fdc_generated(from: "ExternalJob", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Mechanic` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  mechanic_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Mechanic_Data!]!
  ): [Mechanic_KeyOutput!]! @fdc_generated(from: "Mechanic", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `OrderPart` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  orderPart_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [OrderPart_Data!]!
  ): [OrderPart_KeyOutput!]! @fdc_generated(from: "OrderPart", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `OrderService` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  orderService_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [OrderService_Data!]!
  ): [OrderService_KeyOutput!]! @fdc_generated(from: "OrderService", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Part` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  part_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Part_Data!]!
  ): [Part_KeyOutput!]! @fdc_generated(from: "Part", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ServiceCategory` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  serviceCategory_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ServiceCategory_Data!]!
  ): [ServiceCategory_KeyOutput!]! @fdc_generated(from: "ServiceCategory", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StockMovement` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  stockMovement_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StockMovement_Data!]!
  ): [StockMovement_KeyOutput!]! @fdc_generated(from: "StockMovement", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserProfile` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userProfile_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserProfile_Data!]!
  ): [UserProfile_KeyOutput!]! @fdc_generated(from: "UserProfile", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Vehicle` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vehicle_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Vehicle_Data!]!
  ): [Vehicle_KeyOutput!]! @fdc_generated(from: "Vehicle", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorkOrder` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workOrder_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorkOrder_Data!]!
  ): [WorkOrder_KeyOutput!]! @fdc_generated(from: "WorkOrder", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorkshopService` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workshopService_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorkshopService_Data!]!
  ): [WorkshopService_KeyOutput!]! @fdc_generated(from: "WorkshopService", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Client` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Client`.
  """
  client_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Client_Data!
  ): Client_KeyOutput! @fdc_generated(from: "Client", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ExternalJob` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ExternalJob`.
  """
  externalJob_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ExternalJob_Data!
  ): ExternalJob_KeyOutput! @fdc_generated(from: "ExternalJob", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Mechanic` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Mechanic`.
  """
  mechanic_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Mechanic_Data!
  ): Mechanic_KeyOutput! @fdc_generated(from: "Mechanic", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `OrderPart` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `OrderPart`.
  """
  orderPart_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: OrderPart_Data!
  ): OrderPart_KeyOutput! @fdc_generated(from: "OrderPart", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `OrderService` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `OrderService`.
  """
  orderService_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: OrderService_Data!
  ): OrderService_KeyOutput! @fdc_generated(from: "OrderService", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Part` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Part`.
  """
  part_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Part_Data!
  ): Part_KeyOutput! @fdc_generated(from: "Part", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ServiceCategory` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ServiceCategory`.
  """
  serviceCategory_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ServiceCategory_Data!
  ): ServiceCategory_KeyOutput! @fdc_generated(from: "ServiceCategory", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StockMovement` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StockMovement`.
  """
  stockMovement_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StockMovement_Data!
  ): StockMovement_KeyOutput! @fdc_generated(from: "StockMovement", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserProfile` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserProfile`.
  """
  userProfile_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserProfile_Data!
  ): UserProfile_KeyOutput! @fdc_generated(from: "UserProfile", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Vehicle` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vehicle`.
  """
  vehicle_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput! @fdc_generated(from: "Vehicle", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorkOrder` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkOrder`.
  """
  workOrder_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorkOrder_Data!
  ): WorkOrder_KeyOutput! @fdc_generated(from: "WorkOrder", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorkshopService` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkshopService`.
  """
  workshopService_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorkshopService_Data!
  ): WorkshopService_KeyOutput! @fdc_generated(from: "WorkshopService", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Client` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Client`.
  """
  client_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Client_Data!]!
  ): [Client_KeyOutput!]! @fdc_generated(from: "Client", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ExternalJob` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ExternalJob`.
  """
  externalJob_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ExternalJob_Data!]!
  ): [ExternalJob_KeyOutput!]! @fdc_generated(from: "ExternalJob", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Mechanic` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Mechanic`.
  """
  mechanic_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Mechanic_Data!]!
  ): [Mechanic_KeyOutput!]! @fdc_generated(from: "Mechanic", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `OrderPart` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `OrderPart`.
  """
  orderPart_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [OrderPart_Data!]!
  ): [OrderPart_KeyOutput!]! @fdc_generated(from: "OrderPart", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `OrderService` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `OrderService`.
  """
  orderService_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [OrderService_Data!]!
  ): [OrderService_KeyOutput!]! @fdc_generated(from: "OrderService", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Part` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Part`.
  """
  part_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Part_Data!]!
  ): [Part_KeyOutput!]! @fdc_generated(from: "Part", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ServiceCategory` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ServiceCategory`.
  """
  serviceCategory_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ServiceCategory_Data!]!
  ): [ServiceCategory_KeyOutput!]! @fdc_generated(from: "ServiceCategory", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StockMovement` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StockMovement`.
  """
  stockMovement_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StockMovement_Data!]!
  ): [StockMovement_KeyOutput!]! @fdc_generated(from: "StockMovement", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserProfile` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserProfile`.
  """
  userProfile_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserProfile_Data!]!
  ): [UserProfile_KeyOutput!]! @fdc_generated(from: "UserProfile", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Vehicle` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vehicle`.
  """
  vehicle_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Vehicle_Data!]!
  ): [Vehicle_KeyOutput!]! @fdc_generated(from: "Vehicle", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorkOrder` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkOrder`.
  """
  workOrder_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorkOrder_Data!]!
  ): [WorkOrder_KeyOutput!]! @fdc_generated(from: "WorkOrder", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorkshopService` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkshopService`.
  """
  workshopService_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorkshopService_Data!]!
  ): [WorkshopService_KeyOutput!]! @fdc_generated(from: "WorkshopService", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Client` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Client` or `null` if not found.
  """
  client_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Client_Data!
  ): Client_KeyOutput @fdc_generated(from: "Client", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ExternalJob` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ExternalJob` or `null` if not found.
  """
  externalJob_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ExternalJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ExternalJob_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ExternalJob_Data!
  ): ExternalJob_KeyOutput @fdc_generated(from: "ExternalJob", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Mechanic` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Mechanic` or `null` if not found.
  """
  mechanic_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Mechanic_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Mechanic_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Mechanic_Data!
  ): Mechanic_KeyOutput @fdc_generated(from: "Mechanic", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `OrderPart` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `OrderPart` or `null` if not found.
  """
  orderPart_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrderPart_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrderPart_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: OrderPart_Data!
  ): OrderPart_KeyOutput @fdc_generated(from: "OrderPart", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `OrderService` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `OrderService` or `null` if not found.
  """
  orderService_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrderService_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrderService_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: OrderService_Data!
  ): OrderService_KeyOutput @fdc_generated(from: "OrderService", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Part` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Part` or `null` if not found.
  """
  part_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Part_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Part_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Part_Data!
  ): Part_KeyOutput @fdc_generated(from: "Part", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ServiceCategory` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ServiceCategory` or `null` if not found.
  """
  serviceCategory_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ServiceCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ServiceCategory_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ServiceCategory_Data!
  ): ServiceCategory_KeyOutput @fdc_generated(from: "ServiceCategory", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StockMovement` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StockMovement` or `null` if not found.
  """
  stockMovement_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StockMovement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StockMovement_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StockMovement_Data!
  ): StockMovement_KeyOutput @fdc_generated(from: "StockMovement", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserProfile` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserProfile` or `null` if not found.
  """
  userProfile_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: UserProfile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserProfile_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserProfile_Data!
  ): UserProfile_KeyOutput @fdc_generated(from: "UserProfile", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Vehicle` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Vehicle` or `null` if not found.
  """
  vehicle_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput @fdc_generated(from: "Vehicle", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorkOrder` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorkOrder` or `null` if not found.
  """
  workOrder_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkOrder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkOrder_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorkOrder_Data!
  ): WorkOrder_KeyOutput @fdc_generated(from: "WorkOrder", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorkshopService` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorkshopService` or `null` if not found.
  """
  workshopService_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkshopService_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkshopService_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorkshopService_Data!
  ): WorkshopService_KeyOutput @fdc_generated(from: "WorkshopService", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Client` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  client_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Client_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Client_Data!
  ): Int! @fdc_generated(from: "Client", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ExternalJob` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  externalJob_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ExternalJob_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ExternalJob_Data!
  ): Int! @fdc_generated(from: "ExternalJob", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Mechanic` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  mechanic_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Mechanic_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Mechanic_Data!
  ): Int! @fdc_generated(from: "Mechanic", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `OrderPart` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  orderPart_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: OrderPart_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: OrderPart_Data!
  ): Int! @fdc_generated(from: "OrderPart", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `OrderService` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  orderService_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: OrderService_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: OrderService_Data!
  ): Int! @fdc_generated(from: "OrderService", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Part` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  part_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Part_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Part_Data!
  ): Int! @fdc_generated(from: "Part", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ServiceCategory` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  serviceCategory_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ServiceCategory_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ServiceCategory_Data!
  ): Int! @fdc_generated(from: "ServiceCategory", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StockMovement` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  stockMovement_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StockMovement_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StockMovement_Data!
  ): Int! @fdc_generated(from: "StockMovement", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserProfile` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userProfile_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserProfile_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserProfile_Data!
  ): Int! @fdc_generated(from: "UserProfile", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Vehicle` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  vehicle_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Vehicle_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Vehicle_Data!
  ): Int! @fdc_generated(from: "Vehicle", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorkOrder` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workOrder_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorkOrder_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorkOrder_Data!
  ): Int! @fdc_generated(from: "WorkOrder", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorkshopService` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workshopService_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorkshopService_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorkshopService_Data!
  ): Int! @fdc_generated(from: "WorkshopService", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Client` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  client_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow
  ): Client_KeyOutput @fdc_generated(from: "Client", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ExternalJob` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  externalJob_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ExternalJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ExternalJob_FirstRow
  ): ExternalJob_KeyOutput @fdc_generated(from: "ExternalJob", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Mechanic` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  mechanic_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Mechanic_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Mechanic_FirstRow
  ): Mechanic_KeyOutput @fdc_generated(from: "Mechanic", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `OrderPart` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  orderPart_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrderPart_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrderPart_FirstRow
  ): OrderPart_KeyOutput @fdc_generated(from: "OrderPart", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `OrderService` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  orderService_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrderService_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrderService_FirstRow
  ): OrderService_KeyOutput @fdc_generated(from: "OrderService", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Part` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  part_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Part_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Part_FirstRow
  ): Part_KeyOutput @fdc_generated(from: "Part", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ServiceCategory` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  serviceCategory_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ServiceCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ServiceCategory_FirstRow
  ): ServiceCategory_KeyOutput @fdc_generated(from: "ServiceCategory", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StockMovement` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  stockMovement_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StockMovement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StockMovement_FirstRow
  ): StockMovement_KeyOutput @fdc_generated(from: "StockMovement", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserProfile` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userProfile_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: UserProfile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserProfile_FirstRow
  ): UserProfile_KeyOutput @fdc_generated(from: "UserProfile", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Vehicle` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  vehicle_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow
  ): Vehicle_KeyOutput @fdc_generated(from: "Vehicle", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorkOrder` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workOrder_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkOrder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkOrder_FirstRow
  ): WorkOrder_KeyOutput @fdc_generated(from: "WorkOrder", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorkshopService` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workshopService_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkshopService_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkshopService_FirstRow
  ): WorkshopService_KeyOutput @fdc_generated(from: "WorkshopService", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Client` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  client_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Client_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Client", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ExternalJob` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  externalJob_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ExternalJob_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ExternalJob", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Mechanic` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  mechanic_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Mechanic_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Mechanic", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `OrderPart` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  orderPart_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: OrderPart_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "OrderPart", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `OrderService` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  orderService_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: OrderService_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "OrderService", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Part` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  part_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Part_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Part", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ServiceCategory` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  serviceCategory_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ServiceCategory_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ServiceCategory", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StockMovement` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  stockMovement_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StockMovement_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StockMovement", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserProfile` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userProfile_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserProfile_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserProfile", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Vehicle` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  vehicle_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Vehicle_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorkOrder` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workOrder_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorkOrder_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorkOrder", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorkshopService` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workshopService_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorkshopService_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorkshopService", purpose: DELETE_MULTIPLE)
}
