extend type Mutation {
  """
  ✨ Insert a single `Client` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  client_insert(
    """
    Data object to insert into the table.
    """
    data: Client_Data!
  ): Client_KeyOutput! @fdc_generated(from: "Client", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Vehicle` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vehicle_insert(
    """
    Data object to insert into the table.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput! @fdc_generated(from: "Vehicle", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Client` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  client_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Client_Data!]!
  ): [Client_KeyOutput!]! @fdc_generated(from: "Client", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Vehicle` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vehicle_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Vehicle_Data!]!
  ): [Vehicle_KeyOutput!]! @fdc_generated(from: "Vehicle", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Client` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Client`.
  """
  client_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Client_Data!
  ): Client_KeyOutput! @fdc_generated(from: "Client", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Vehicle` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vehicle`.
  """
  vehicle_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput! @fdc_generated(from: "Vehicle", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Client` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Client`.
  """
  client_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Client_Data!]!
  ): [Client_KeyOutput!]! @fdc_generated(from: "Client", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Vehicle` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vehicle`.
  """
  vehicle_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Vehicle_Data!]!
  ): [Vehicle_KeyOutput!]! @fdc_generated(from: "Vehicle", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Client` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Client` or `null` if not found.
  """
  client_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Client_Data!
  ): Client_KeyOutput @fdc_generated(from: "Client", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Vehicle` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Vehicle` or `null` if not found.
  """
  vehicle_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Vehicle_Data!
  ): Vehicle_KeyOutput @fdc_generated(from: "Vehicle", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Client` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  client_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Client_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Client_Data!
  ): Int! @fdc_generated(from: "Client", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Vehicle` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  vehicle_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Vehicle_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Vehicle_Data!
  ): Int! @fdc_generated(from: "Vehicle", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Client` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  client_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow
  ): Client_KeyOutput @fdc_generated(from: "Client", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Vehicle` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  vehicle_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow
  ): Vehicle_KeyOutput @fdc_generated(from: "Vehicle", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Client` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  client_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Client_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Client", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Vehicle` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  vehicle_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Vehicle_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle", purpose: DELETE_MULTIPLE)
}
