extend type Client {
  """
  ✨ List `Vehicle` objects in a one-to-many relationship (where `Vehicle`.`client` is this object).
  """
  vehicles_on_client(
    """
    Filter condition to narrow down the query results.
    """
    where: Vehicle_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Vehicle_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Vehicle_Having
  ): [Vehicle!]! @fdc_generated(from: "Vehicle.client", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Client", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Client` table.
  """
  _count: Int! @fdc_generated(from: "Client.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `active` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  active_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.active", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `address` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  address_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.address", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `creditLimit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  creditLimit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.creditLimit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `documentNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  documentNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.documentNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `documentType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  documentType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.documentType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `phone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.phone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `segment` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  segment_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.segment", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.type", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Client` table where the `workshopId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  workshopId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Client.workshopId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `creditLimit` field in the `Client` table.
  """
  creditLimit_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Client.creditLimit", purpose: QUERY_SUM)
  """
  ✨ Average the `creditLimit` field in the `Client` table.
  """
  creditLimit_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Client.creditLimit", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Client` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Client.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `creditLimit` field in the `Client` table.
  """
  creditLimit_min: Float @fdc_generated(from: "Client.creditLimit", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Client` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Client.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Client` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Client.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `creditLimit` field in the `Client` table.
  """
  creditLimit_max: Float @fdc_generated(from: "Client.creditLimit", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Client` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Client.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Client.id", purpose: ENTITY_ID)
}
extend type Vehicle {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Vehicle", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Vehicle` table.
  """
  _count: Int! @fdc_generated(from: "Vehicle.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `active` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  active_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.active", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `brand` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  brand_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.brand", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `clientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.clientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `color` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  color_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.color", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `fuelType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fuelType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.fuelType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `mileage` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  mileage_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.mileage", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `model` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  model_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.model", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `plate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  plate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.plate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `vin` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  vin_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.vin", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `workshopId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  workshopId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.workshopId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Vehicle` table where the `year` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  year_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Vehicle.year", purpose: QUERY_COUNT)
  """
  ✨ Sum the `mileage` field in the `Vehicle` table.
  """
  mileage_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Vehicle.mileage", purpose: QUERY_SUM)
  """
  ✨ Sum the `year` field in the `Vehicle` table.
  """
  year_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Vehicle.year", purpose: QUERY_SUM)
  """
  ✨ Average the `mileage` field in the `Vehicle` table.
  """
  mileage_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Vehicle.mileage", purpose: QUERY_AVG)
  """
  ✨ Average the `year` field in the `Vehicle` table.
  """
  year_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Vehicle.year", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Vehicle` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Vehicle.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `mileage` field in the `Vehicle` table.
  """
  mileage_min: Int @fdc_generated(from: "Vehicle.mileage", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Vehicle` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Vehicle.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `year` field in the `Vehicle` table.
  """
  year_min: Int @fdc_generated(from: "Vehicle.year", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Vehicle` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Vehicle.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `mileage` field in the `Vehicle` table.
  """
  mileage_max: Int @fdc_generated(from: "Vehicle.mileage", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Vehicle` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Vehicle.updatedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `year` field in the `Vehicle` table.
  """
  year_max: Int @fdc_generated(from: "Vehicle.year", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Vehicle.id", purpose: ENTITY_ID)
}
